<style type="text/css">
<!--
body {
    margin-left: 0px;
	margin-top: <?php echo $config['margin-top']?>;
	margin-right: 0px;
	margin-bottom: <?php echo $config['margin-bottom']?>;
	background-color: <?php echo $config['background-color']?>;
	text-align:center;
}
table {
	font-size:16px;
	line-height: <?php echo $config['line-height']?>px;
}
td.info {
	font-size:12px;
	line-height: <?php echo $config['line-height']?>px;
    color:#999999
}
A:link {
	FONT-WEIGHT: bold; FONT-SIZE: 12px; COLOR: #933; TEXT-DECORATION: none
}
A:visited {
	FONT-WEIGHT: bold; FONT-SIZE: 12px; COLOR: #933; TEXT-DECORATION: none
}
A:hover {
	FONT-WEIGHT: bold; COLOR: #f33; TEXT-DECORATION: underline
}
A:active {
	FONT-WEIGHT: bold; COLOR: #33f; TEXT-DECORATION: none
}
H1 {
	FONT-WEIGHT: bold; MARGIN: 2px 0px; FONT-FAMILY: 'Trebuchet MS', 'Gill Sans', Helvetica, sans-serif
}
H2 {
	FONT-WEIGHT: bold; MARGIN: 2px 0px; FONT-FAMILY: 'Trebuchet MS', 'Gill Sans', Helvetica, sans-serif
}
H3 {
	FONT-WEIGHT: bold; MARGIN: 2px 0px; FONT-FAMILY: 'Trebuchet MS', 'Gill Sans', Helvetica, sans-serif
}
H4 {
	FONT-WEIGHT: bold; MARGIN: 2px 0px; FONT-FAMILY: 'Trebuchet MS', 'Gill Sans', Helvetica, sans-serif
}
H5 {
	FONT-WEIGHT: bold; MARGIN: 2px 0px; FONT-FAMILY: 'Trebuchet MS', 'Gill Sans', Helvetica, sans-serif
}
H6 {
	FONT-WEIGHT: bold; MARGIN: 2px 0px; FONT-FAMILY: 'Trebuchet MS', 'Gill Sans', Helvetica, sans-serif
}
H1 {
	FONT-WEIGHT: bold; FONT-SIZE: 20px
}
H2 {
	FONT-WEIGHT: bold; FONT-SIZE: 18px
}
H3 {
	FONT-WEIGHT: bold; FONT-SIZE: 16px
}
H4 {
	FONT-WEIGHT: bold; FONT-SIZE: 14px
}
H5 {
	FONT-WEIGHT: bold; FONT-SIZE: 12px
}
H6 {
	FONT-WEIGHT: bold; FONT-SIZE: 10px
}
-->
</style>
